# Generated by Django 3.1.7 on 2021-03-25 09:37

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields
import model_utils.fields
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', model_utils.fields.StatusField(choices=[('draft', 'draft'), ('published', 'published'), ('removed', 'removed')], default='draft', max_length=100, no_check_for_status=True)),
                ('status_changed', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Name')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='full_name', verbose_name='Slug')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('title', models.CharField(max_length=150, verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is activated ?')),
                ('link_facebook', models.URLField(blank=True, null=True, verbose_name='Facebook link')),
                ('link_instagram', models.URLField(blank=True, null=True, verbose_name='Instagram link')),
                ('link_linkedin', models.URLField(blank=True, null=True, verbose_name='LinkdeIn profile link')),
                ('link_snapchat', models.URLField(blank=True, null=True, verbose_name='Link snapchat account')),
                ('link_telegram', models.URLField(blank=True, null=True, verbose_name='Telegram link')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Date updated')),
                ('category', models.ManyToManyField(blank=True, related_name='jobs', to='job.Category', verbose_name='Categories')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Job',
                'verbose_name_plural': 'Jobs',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Phone Number')),
                ('country', django_countries.fields.CountryField(default='CM', max_length=2, verbose_name='Countries')),
                ('has_whatsapp', models.BooleanField(default=False, verbose_name='Is used for WhatsApp ?')),
                ('discuss_link', models.URLField(blank=True, null=True, verbose_name='Link for WhatsApp discuss')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Activated ?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Date updated')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='job.job')),
            ],
            options={
                'verbose_name': 'Phone Number',
                'verbose_name_plural': 'Phone Numbers',
                'ordering': ['phone'],
            },
        ),
        migrations.CreateModel(
            name='EmailAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Activated ?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Date updated')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='job.job')),
            ],
            options={
                'verbose_name': 'Email',
                'verbose_name_plural': 'Email',
                'ordering': ['email'],
            },
        ),
    ]
