# Generated by Django 3.1.4 on 2021-03-06 23:08

from django.db import migrations, models
import django_countries.fields
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Username')),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, null=True, unique=True, verbose_name='Email')),
                ('first_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='First name')),
                ('last_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Last name')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Birth Date')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Phone Number')),
                ('country', django_countries.fields.CountryField(default='CM', max_length=2, verbose_name='Countries')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Is Staff ?')),
                ('is_active', models.BooleanField(default=False, verbose_name='Is Activated ?')),
                ('activation_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Activation Key')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Date of inscription')),
                ('date_update', models.DateTimeField(auto_now_add=True, verbose_name='Date Updated')),
                ('user_condition_is_read', models.BooleanField(default=False, verbose_name='User conditions is read ?')),
                ('profile_picture', models.ImageField(null=True, upload_to='photo_user/', verbose_name='Profile Picture')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
    ]
